### ISSUE TITLE
Fix HPA readout

### ISSUE THREAD

**Issue by bm98** [bm98/dump1090#1]
a. above FL200 everybody is using QNE (std setting 29.92’’ Hg or 1013.2 hpa) baro altimeter setting (actually upon passing trans.alt - departure aerodrome till trans. level - arrival irport).
in this figure it shows 1010hpa so either aircraft setting wrong or more likely data presentation issue (more likely). so maybe change the code for all above FL200 to display 1013.2hpa / 29.92’’

**Comment by bm98** [comment]
Fixed in latest

**Comment by Systemac** [comment]
Hello, first of all thanks for the handy tool, is there going to be a version for the 3.3 in ptu???
